# Generated by Django 5.1.4 on 2024-12-14 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('picture_large', models.URLField()),
                ('picture_medium', models.URLField()),
                ('picture_thumbnail', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('expired_at', models.DateField()),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('board', models.CharField(max_length=100)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.assigneduser')),
            ],
        ),
    ]
